resolver: nightly-2018-09-01 # GHC 8.4.3
packages:
- .
- hie-plugin-api

extra-deps:
- ./submodules/brittany
- ./submodules/HaRe
- ./submodules/ghc-mod
- ./submodules/ghc-mod/core
- ./submodules/haskell-lsp
- ./submodules/haskell-lsp/haskell-lsp-types
- aeson-1.3.1.1
# - apply-refact-0.5.0.0
- base-compat-0.9.3
- base-orphans-0.7
# - brittany-0.11.0.0
- cabal-helper-0.8.1.0@rev:0
- cabal-plan-0.3.0.0
- constrained-dynamic-0.1.0.0
- ekg-0.4.0.15
- ekg-json-0.1.0.6
- ghc-exactprint-0.5.8.0
- haddock-api-2.20.0
- hsimport-0.8.6
- monad-memo-0.4.1
- lsp-test-0.4.0.0
- semigroupoids-5.2.2
- syz-0.2.0.0
- temporary-1.2.1.1
- yaml-0.8.32

flags:
  haskell-ide-engine:
    pedantic: true
  hie-plugin-api:
    pedantic: true

nix:
  packages: [ icu libcxx zlib ]

concurrent-tests: false
