resolver: nightly-2018-12-25 # GHC 8.6.3
packages:
- .
- hie-plugin-api

extra-deps:
- ./submodules/HaRe
- ./submodules/brittany
- ./submodules/cabal-helper
- ./submodules/ghc-mod
- ./submodules/ghc-mod/core

  #- apply-refact-0.6.0.0
  #- butcher-1.3.2.1
  #- cabal-plan-0.4.0.0
  #- constrained-dynamic-0.1.0.0
  #- ekg-json-0.1.0.6
  #- ekg-wai-0.1.0.3
  #- haddock-api-2.21.0
  #- hsimport-0.8.6
  #- monad-memo-0.4.1
  #- multistate-0.8.0.1
  #- resolv-0.1.1.2
  #- lsp-test-0.5.0.2
  #- pretty-show-1.8.2
  #- syz-0.2.0.0
  #- temporary-1.2.1.1
  #- yaml-0.8.32

- butcher-1.3.2.1
- cabal-plan-0.5.0.0
- constrained-dynamic-0.1.0.0
- ekg-wai-0.1.0.3
- haddock-api-2.21.0
- hsimport-0.8.6
#- monad-memo-0.4.1@sha256:d7575b0c89ad21818ca5746170d10a3b92f01fdf9028fa37d3a370e42b24b38b
- multistate-0.8.0.1
- syz-0.2.0.0
#- temporary-1.2.1.1@sha256:7a53ecaa3883429616ffe8b680e97195c6a45598b77171d070b9c01ffaadce0b
#- yaml-0.8.32@sha256:691cbf4f6a362df5a76464f42e328c99723f3d525767e3a1e78ee112ab723f7a
- ekg-json-0.1.0.6

flags:
  haskell-ide-engine:
    pedantic: true
  hie-plugin-api:
    pedantic: true
  # ekg-core:
  #   allow-newer: true
  # ekg-json:
  #   allow-newer: true
  # ekg-wai:
  #   allow-newer: true
  # base:
  #   allow-newer: true
  # process:
  #   allow-newer: true

# allow-newer: true

nix:
  packages: [ icu libcxx zlib ]

concurrent-tests: false
